Repository april-tools/cirkit, pull requests merged in 2024-12, with the labels that each got.

#326 Cleaning up
  cirkit/symbolic/circuit.py
  cirkit/symbolic/io.py
  cirkit/templates/circuit_templates/utils.py
  cirkit/templates/logic/__init__.py
  cirkit/templates/logic/graph.py
  cirkit/templates/logic/sdd.py
  cirkit/templates/logic/utils.py
  cirkit/templates/pgms.py
  cirkit/templates/region_graph/graph.py
  cirkit/templates/utils.py
  pyproject.toml
  tests/backend/torch/test_compile_circuit.py
  tests/symbolic/test_from_region_graph.py
Labels: enhancement

#323 Mkdocs math support + more and better docstrings + interfaces fix
  cirkit/backend/torch/circuits.py
  cirkit/backend/torch/graph/modules.py
  cirkit/backend/torch/layers/base.py
  cirkit/backend/torch/layers/inner.py
  cirkit/backend/torch/layers/input.py
  cirkit/backend/torch/layers/optimized.py
  cirkit/backend/torch/parameters/nodes.py
  cirkit/backend/torch/parameters/parameter.py
  cirkit/backend/torch/queries.py
  cirkit/backend/torch/rules/layers.py
  cirkit/symbolic/circuit.py
  cirkit/symbolic/functional.py
  cirkit/symbolic/layers.py
  cirkit/symbolic/parameters.py
  cirkit/templates/logic/graph.py
  cirkit/utils/algorithms.py
  docs/js/katex.js
  mkdocs.yml
Labels: documentation

#328 MNIST Classification notebook
  cirkit/templates/data_modalities.py
  docs/index.md
  docs/notebooks/generative-vs-discriminative-circuit.ipynb
  mkdocs.yml
  notebooks/README.md
  notebooks/generative-vs-discriminative-circuit.ipynb
Labels: documentation

#330 Avoid OOM and speed up training in SOS circuits
  cirkit/__init__.py
  cirkit/backend/__init__.py
  cirkit/backend/torch/circuits.py
  cirkit/backend/torch/compiler.py
  cirkit/backend/torch/graph/modules.py
  cirkit/backend/torch/graph/optimize.py
  cirkit/backend/torch/initializers.py
  cirkit/backend/torch/layers/base.py
  cirkit/backend/torch/layers/inner.py
  cirkit/backend/torch/layers/input.py
  cirkit/backend/torch/layers/optimized.py
  cirkit/backend/torch/optimization/parameters.py
  cirkit/backend/torch/parameters/nodes.py
  cirkit/backend/torch/parameters/optimized.py
  cirkit/backend/torch/parameters/parameter.py
  cirkit/backend/torch/parameters/pic.py
  cirkit/backend/torch/queries.py
  cirkit/symbolic/__init__.py
  cirkit/symbolic/operators.py
  cirkit/templates/__init__.py
  cirkit/templates/logic/graph.py
  cirkit/templates/utils.py
  cirkit/utils/algorithms.py
  tests/symbolic/test_circuit_operators.py
  tests/symbolic/test_utils.py
  tests/templates/region_graph/test_utils.py
Labels: enhancement

#329 Upgrade to numpy 2.x and add opt_einsum
  pyproject.toml
Labels: enhancement, repository
